# Generated by Django 3.1.4 on 2020-12-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_stuff_system', '0004_todo_finish_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='finish_by',
        ),
    ]
