# Generated by Django 3.1.4 on 2020-12-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_stuff_system', '0005_auto_20201213_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='company',
            field=models.ForeignKey(blank=True, default='empty', null=True, on_delete=django.db.models.deletion.CASCADE, to='base_stuff_system.company'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(blank=True, default='empty', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
