# Generated by Django 3.1.4 on 2020-12-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stuff_system', '0005_remove_todo_finish_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='date_of_birth',
            field=models.DateField(help_text='Please use the following format: <em>%d/%m/%Y</em>.'),
        ),
    ]
