# Generated by Django 3.1.3 on 2020-12-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestuff', '0002_auto_20201211_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendbaseuser',
            name='image',
            field=models.ImageField(blank=True, default='../static/default.jpg', upload_to='profiles/<django.db.models.fields.CharField>/'),
        ),
    ]
