# Generated by Django 3.1.3 on 2020-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestuff', '0002_auto_20201123_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendbaseuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='extendbaseuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
