# Generated by Django 3.1.3 on 2020-11-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestuff', '0003_auto_20201123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendbaseuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'teacher'), (2, 'student')], default=1, max_length=10),
        ),
    ]
