# Generated by Django 3.1.3 on 2020-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestuff', '0004_auto_20201123_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendbaseuser',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default=1, max_length=10),
        ),
    ]
