# Generated by Django 3.1.3 on 2020-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestuff', '0005_auto_20201212_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendbaseuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/<django.db.models.fields.CharField>/'),
        ),
    ]
