# Generated by Django 3.1.4 on 2020-12-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_stuff_system', '0003_auto_20201218_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finish_by',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
